version: 1
formatters:
    simple:
        format: '%(asctime)s %(name)s: %(message)s'
    extended:
        format: '%(asctime)s %(name)s %(levelno)s %(filename)s || %(levelname)s || %(message)s'
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: 'ext://sys.stdout'
    file_handler:
        class: logging.FileHandler
        level: DEBUG
        filename: Test.log
        formatter: extended
loggers:
    dev:
        handlers:
            - console
            - file_handler
    test:
        handlers:
            - file_handler
root:
    handlers:
        - file_handler
